Sylius\Component\Product\Model\ProductVariant:
    exclusion_policy: ALL
    xml_root_name: variant
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true 
            type: string 
            groups: [Detailed, Default] 
        position:
            expose: true 
            type: integer 
            groups: [Detailed, Default] 
        optionValues:
            expose: true 
            type: array 
            groups: [Detailed] 
        translations:
            expose: true 
            type: array 
            groups: [Detailed] 
