sylius_user_registration:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: sylius_customer_registration
            event: register
            template: SyliusCustomerBundle::register.html.twig
            redirect: referer
            permission: false
