# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_managing_customers:
            contexts_as_services:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.customer
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.security
                - sylius.behat.context.setup.customer
                - sylius.behat.context.setup.user

                - sylius.behat.context.ui.admin.managing_customers
                - sylius.behat.context.ui.admin.notification
            filters:
                tags: "@managing_customers && @ui"
