# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_registering:
            contexts_as_services:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.user

                - sylius.behat.context.ui.user
            filters:
                tags: "@registering && @ui"
